language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - 'hhvm'

services:
  - 'mysql'

before_script:
  - mysql -u root -e 'create database IF NOT EXISTS loginlib;'

script: php ./test/compileLoginLib.php
