dist: trusty
sudo: required

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
<<<<<<< HEAD

script: php ./test/compileLoginLib.php

services:
  - mysql
  
before_script:
  - mysql -e 'create database loginlib;'
=======
  - 'hhvm'

script: php ./compile/compile.php

notifications:
  email: false

before_script:
  - mysql -u root -e 'create database loginlib;'
>>>>>>> refs/heads/develop
